#! /bin/sh

#RESIZE VM WINDOW (TEMPORARY -- REMOVE WHEN USED AS PERM)
xrandr -s 1600x900

#SXHKD INIT
pgrep -x sxhkd > /dev/null
pkill sxhkd 
sxhkd &

#POLYBAR
~/.config/polybar/launch.sh

#NITROGEN
nitrogen --restore &

#PICOM
picom -b

#BSP Config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
